module.exports = {

  final_results_response: {

    "message": "SUCCESS: Result available",
    "status": "done",
    "status_code": 3,
    "result": {
      "establishment": "Morrisons",
      "validatedEstablishment": true,
      "date": "",
      "total": "14.300",
      "url": "",
      "phoneNumber": "01983 822419",
      "paymentMethod": "Mastercard",
      "address": "Isle of Wight - Newport, South Street, Newport, PO30 1JQ",
      "cash": "0.000",
      "change": "0.000",
      "validatedTotal": false,
      "subTotal": "14.300",
      "validatedSubTotal": true,
      "tax": "0.000",
      "taxes": [],
      "discount": "0.000",
      "rounding": "0.000",
      "discounts": [],
      "lineItems": [{
        "qty": 2,
        "desc": "2 M EGG FRIED NOODLES £1.00",
        "unit": "",
        "price": "0.000",
        "symbols": ["£"],
        "discount": "0.000",
        "lineType": "",
        "descClean": "M EGG FRIED NOODLES £1.00",
        "lineTotal": "2.000",
        "productCode": "",
        "customFields": {}
      }, {
        "qty": 1,
        "desc": "1 M CHINESE TAKEAWAY £2.00",
        "unit": "",
        "price": "0.000",
        "symbols": ["€", "F"],
        "discount": "0.000",
        "lineType": "",
        "descClean": "M CHINESE TAKEAWAY £2.00",
        "lineTotal": "2.000",
        "productCode": "",
        "customFields": {}
      }, {
        "qty": 1,
        "desc": "1 ' M ' CHILLI CHICKEN £2.00",
        "unit": "",
        "price": "0.000",
        "symbols": ["€", "F"],
        "discount": "0.000",
        "lineType": "",
        "descClean": "' M ' CHILLI CHICKEN £2.00",
        "lineTotal": "2.000",
        "productCode": "",
        "customFields": {}
      }, {
        "qty": 1,
        "desc": "1 M CURRY TAKEAWAY £2.00",
        "unit": "",
        "price": "0.000",
        "symbols": ["€", "F"],
        "discount": "0.000",
        "lineType": "",
        "descClean": "M CURRY TAKEAWAY £2.00",
        "lineTotal": "2.000",
        "productCode": "",
        "customFields": {}
      }, {
        "qty": 1,
        "desc": "1 M CHICKEN TAKEAWAY $ 2.00",
        "unit": "",
        "price": "2.000",
        "symbols": ["€", "F"],
        "discount": "0.000",
        "lineType": "",
        "descClean": "M CHICKEN TAKEAWAY $",
        "lineTotal": "2.000",
        "productCode": "",
        "customFields": {}
      }, {
        "qty": 1,
        "desc": "1 M EGG FRIED RICE $ 1.00",
        "unit": "",
        "price": "1.000",
        "symbols": ["£", "F"],
        "discount": "0.000",
        "lineType": "",
        "descClean": "M EGG FRIED RICE $",
        "lineTotal": "1.000",
        "productCode": "",
        "customFields": {}
      }, {
        "qty": 1,
        "desc": "1 M DRIED SKIMMED MILK £1.75",
        "unit": "",
        "price": "0.000",
        "symbols": ["€", "F"],
        "discount": "0.000",
        "lineType": "",
        "descClean": "M DRIED SKIMMED MILK £1.75",
        "lineTotal": "1.750",
        "productCode": "",
        "customFields": {}
      }, {
        "qty": 1,
        "desc": "1 M DOUGHNUTS £1.10",
        "unit": "",
        "price": "0.000",
        "symbols": ["€", "F"],
        "discount": "0.000",
        "lineType": "",
        "descClean": "M DOUGHNUTS £1.10",
        "lineTotal": "1.100",
        "productCode": "",
        "customFields": {}
      }, {
        "qty": 1,
        "desc": "1 M WHOLEMEAL TOASTIE £0.45",
        "unit": "",
        "price": "0.000",
        "symbols": ["€", "F"],
        "discount": "0.000",
        "lineType": "",
        "descClean": "M WHOLEMEAL TOASTIE £0.45",
        "lineTotal": "0.450",
        "productCode": "",
        "customFields": {}
      }],
      "summaryItems": [{
        "qty": 0,
        "desc": "BALANCE DUE",
        "unit": "",
        "price": "0.000",
        "symbols": ["€"],
        "discount": "0.000",
        "lineType": "Total",
        "descClean": "BALANCE DUE",
        "lineTotal": "14.300",
        "productCode": "",
        "customFields": {}
      }, {
        "qty": 0,
        "desc": "Card",
        "unit": "",
        "price": "0.000",
        "symbols": ["€"],
        "discount": "0.000",
        "lineType": "",
        "descClean": "Card",
        "lineTotal": "14.300",
        "productCode": "",
        "customFields": {}
      }],
      "subTotalConfidence": 0.99,
      "taxesConfidence": [],
      "discountConfidences": [],
      "totalConfidence": 0.7,
      "dateConfidence": 0,
      "establishmentConfidence": 0.99,
      "cashConfidence": 0,
      "changeConfidence": 0,
      "roundingConfidence": 0,
      "customFields": {
        "URL": "",
        "Country": "GBR",
        "Currency": "GBP",
        "VATNumber": "",
        "ExpenseType": "",
        "PaymentMethod": "Mastercard",
        "CardLast4Digits": ""
      },
      "documentType": "receipt",
      "currency": "GBP",
      "barcodes": [],
      "addressNorm": {
        "city": "Newport",
        "state": "",
        "number": "",
        "street": "Isle Of Wight Newport South Street",
        "suburb": "",
        "country": "",
        "building": "",
        "postcode": "PO30 1JQ"
      },
      "expenseType": "None",
      "otherData": []
    },
    "success": true,
    "code": 202

  },

  image_uploaded_successfully_response: {
    "message": "SUCCESS: Image uploaded successfully",
    "status": "success",
    "status_code": 2,
    "token": "CMf1WF6cSXPTALs2",
    "success": true,
    "code": 200,
    "duplicate": true,
    "duplicateToken": "CMf1WF6cSXPTALs2"
  },
  image_waiting_processing_response: {
    "message": "WARNING: Result not yet available",
    "status": "pending",
    "status_code": 1,
    "success": true,
    "code": 301
  }
}